// Enumerate color facts independently. No website case names/images/algorithms are imported.
const fs=require('fs'),assert=require('assert/strict'),m=require('./square-one-model.cjs');
function colors(state){return [state.top,state.bottom].map(a=>a.filter((v,i)=>a.indexOf(v)===i).map(v=>v<8?1:0));}
function canonical(layers){let orbit=[];for(let t=0;t<4;t++)for(let b=0;b<4;b++)for(let f=0;f<2;f++){const a=layers[0].slice(t*2).concat(layers[0].slice(0,t*2)),c=layers[1].slice(b*2).concat(layers[1].slice(0,b*2));orbit.push(a.concat(c).map(v=>v^f).join(''));}return orbit.sort()[0];}
const counts=new Map;const bits=n=>Array.from({length:4},(_,i)=>(n>>i)&1),sum=a=>a.reduce((n,v)=>n+v,0);
for(let a=0;a<16;a++)for(let b=0;b<16;b++)for(let c=0;c<16;c++)for(let d=0;d<16;d++){const ac=bits(a),ae=bits(b),bc=bits(c),be=bits(d);if(sum(ac)+sum(bc)!==4||sum(ae)+sum(be)!==4)continue;const k=canonical([ae.flatMap((v,i)=>[v,ac[i]]),bc.flatMap((v,i)=>[v,be[i]])]);counts.set(k,(counts.get(k)||0)+1);}
assert.equal(counts.size,186);assert.equal([...counts.values()].reduce((a,b)=>a+b,0),4900);
const macros=[];const turn=n=>((n+18)%12)-6;for(let a=0;a<4;a++)for(let b=0;b<4;b++){macros.push([[turn(1+3*a),turn(3*b)],'/',[-1,0]]);macros.push([[turn(3*a),turn(-1+3*b)],'/',[0,1]]);}
const queue=[{state:m.solved(),seq:[]}],seen=new Set(),cases=new Map;for(let i=0;i<queue.length;i++){const {state,seq}=queue[i],layer=colors(state),raw=layer.flat().join('');if(seen.has(raw))continue;seen.add(raw);const key=canonical(layer);if(!cases.has(key))cases.set(key,{state,seq});for(const macro of macros){const next=m.apply(macro,structuredClone(state));if(!seen.has(colors(next).flat().join('')))queue.push({state:next,seq:seq.concat(macro)});}}
assert.equal(seen.size,4900);assert.equal(cases.size,186);
const result=[...cases].sort(([a],[b])=>a.localeCompare(b)).map(([key,{state,seq}],i)=>{const solution=m.inverse(seq);assert.deepEqual(m.apply(solution,structuredClone(state)),m.solved());const id='obl_'+key;return {id,displayName:`OBL ${i+1}`,name:`OBL ${i+1}`,subgroup:'',imageKey:'sq1obl_'+id,recognition:'',notes:'Independent cube-shape color-state enumeration; U/D alignment and upper/lower color inversion identified. Reference setup, not a curated speed algorithm or globally slice-optimal solution.',setup:m.format(seq),algorithms:seq.length?[{id:id+'-reference',notation:m.format(solution),isPrimary:true,source:'CubeFlow independent cube-shape orientation enumeration',tags:['reference','inverse-setup']}]:[],nativeState:state,probability:counts.get(key)/4900,probabilityExact:{numerator:counts.get(key),denominator:4900},probabilityBasis:'Uniform cube-shape corner/edge upper-color assignments (4900 states); not empirical solve frequency'};});
fs.writeFileSync('CubeFlow/Resources/Algs/sq1obl.json',JSON.stringify({puzzle:'SQ1',set:'SQ1OBL',version:1,source:'CubeFlow independent enumeration: 4900 color assignments, 186 alignment/color-inversion orbits',cases:result},null,2)+'\n');console.log('OBL',result.length,'full assignments',seen.size);
