const fs=require('fs'),assert=require('assert/strict'),engine=require('../../CubeFlow/Resources/DrawScramble/fto_engine.js');
const root='CubeFlow/Resources/Algs',summary=[];
function steps(s){const a=[];s.split('/').forEach((part,i)=>{if(i)a.push('/');part=part.trim().replace(/^\(/,'').replace(/\)$/,'');if(!part)return;const pair=part.split(',').map(v=>Number(v.trim()));assert.equal(pair.length,2);assert(pair.every(v=>Number.isInteger(v)&&Math.abs(v)<=6));a.push(pair);});return a;}
function sqState(s,state={top:[0,1,1,2,3,3,4,5,5,6,7,7],bottom:[9,9,8,11,11,10,13,13,12,15,15,14],m:0}){for(const step of steps(s)){if(step==='/'){assert([state.top,state.bottom].every(a=>a[0]!==a[11]&&a[5]!==a[6]),'slice splits corner');const half=state.top.slice(6);state.top.splice(6,6,...state.bottom.slice(0,6));state.bottom.splice(0,6,...half);state.m^=1;}else for(const[a,n]of[[state.top,step[0]],[state.bottom,step[1]]])a.push(...a.splice(0,(n+12)%12));}return state;}
const baselineIssues=[];
for(const file of fs.readdirSync(root).filter(f=>f.endsWith('.json')&&f!=='fto_protocol_vectors.json'&&f!=='canonical_relationships.json')){const p=JSON.parse(fs.readFileSync(root+'/'+file));assert(p.puzzle&&p.set&&p.source&&Number.isInteger(p.version)&&p.cases.length);const ids=new Set();
for(const c of p.cases){assert(c.id&&!ids.has(c.id),'duplicate ID '+file+'/'+c.id);ids.add(c.id);assert(c.displayName&&c.name&&c.imageKey);assert(Array.isArray(c.algorithms));const aids=new Set();for(const a of c.algorithms){assert(a.id&&!aids.has(a.id));aids.add(a.id);assert(typeof a.notation==='string'&&(a.notation.trim().length>0||(file==='sq1cs.json'&&c.id==='square_square')));assert(typeof a.isPrimary==='boolean'&&Array.isArray(a.tags));}
if(p.puzzle==='SQ1'&&c.setup){try{const state=sqState(c.setup);if(['sq1pbl.json','sq1pblparity.json','sq1epparity.json','sq1obl.json','sq1csp.json'].includes(file)){assert.deepEqual(state,c.nativeState);if(c.algorithms.length){assert.deepEqual(sqState(c.algorithms[0].notation,structuredClone(state)),sqState(''));assert(c.algorithms[0].tags.includes('reference'));}else assert.deepEqual(state,sqState(''));}}catch(e){if(['sq1pbl.json','sq1pblparity.json','sq1epparity.json','sq1obl.json','sq1csp.json'].includes(file))throw e;baselineIssues.push(file+'/'+c.id+': '+e.message);}}
if(file==='ftoedges.json'){assert.deepEqual(engine.state(c.setup),c.nativeState);assert.deepEqual(engine.state(c.setup+' '+c.algorithms[0].notation),engine.state(''));assert(c.algorithms[0].tags.includes('reference'));}
}
summary.push({file,puzzle:p.puzzle,cases:p.cases.length});}
assert.equal(summary.find(x=>x.file==='sq1pbl.json').cases,967);assert.equal(summary.find(x=>x.file==='ftoedges.json').cases,16);
const known=['lin.json/cb: slice splits corner','sq1cs.json/muffin_right_paw: slice splits corner','sq1eo.json/4_4: slice splits corner','sq1linparitypll.json/cb: slice splits corner'];assert.deepEqual(baselineIssues.sort(),known.sort(),'new baseline alignment exception');
console.log(JSON.stringify({sets:summary.length,cases:summary.reduce((n,x)=>n+x.cases,0),coverage:summary,knownBaselineAlignmentExceptions:baselineIssues},null,2));
